# Generated by Django 5.2.5 on 2025-09-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.DateTimeField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('events', models.ManyToManyField(db_table='book_events', related_name='books', to='core.event')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('photo', 'Photo'), ('youtube', 'YouTube')], max_length=100)),
                ('url', models.CharField(blank=True, help_text='For YouTube: enter video ID (e.g., LDYwIOWbeRU) or full URL', max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.event')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.event')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('events', models.ManyToManyField(db_table='event_tags', related_name='tags', to='core.event')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
